-- Individual, tenant-scoped notifications for newly created appointments.
--
-- This intentionally does not reuse the legacy notifications table: it
-- has a different access model. No customer or appointment data is copied to
-- this table; the browser resolves appointment details through its existing
-- tenant-scoped data access.
--
-- Conceptual rollback order: remove the publication table, drop the trigger,
-- drop private.create_appointment_notifications(), then drop this table.

create table if not exists public.appointment_notifications (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default clock_timestamp(),
  constraint appointment_notifications_membership_fkey
    foreign key (tenant_id, recipient_user_id)
    references public.tenant_memberships(tenant_id, user_id)
    on delete cascade,
  constraint appointment_notifications_recipient_appointment_key
    unique (recipient_user_id, appointment_id)
);

comment on table public.appointment_notifications is
  'Notificacoes individuais de novos agendamentos; sem copia de dados pessoais do cliente.';
comment on column public.appointment_notifications.read_at is
  'Instante em que o destinatario marcou a notificacao como lida; null significa nao lida.';

-- The most common UI queries are recent notifications and the unread badge.
create index if not exists appointment_notifications_recipient_recent_idx
  on public.appointment_notifications (recipient_user_id, created_at desc);
create index if not exists appointment_notifications_recipient_unread_idx
  on public.appointment_notifications (recipient_user_id, created_at desc)
  where read_at is null;
create index if not exists appointment_notifications_appointment_idx
  on public.appointment_notifications (appointment_id);
create index if not exists appointment_notifications_tenant_idx
  on public.appointment_notifications (tenant_id);

alter table public.appointment_notifications enable row level security;

-- Browser clients can neither manufacture nor delete notifications. Column
-- privileges also prevent updates from moving a notification between users,
-- tenants or appointments.
revoke all privileges on table public.appointment_notifications
  from public, anon, authenticated;
grant select on table public.appointment_notifications to authenticated;
grant update (read_at) on table public.appointment_notifications to authenticated;

drop policy if exists appointment_notifications_select_recipient
  on public.appointment_notifications;
create policy appointment_notifications_select_recipient
on public.appointment_notifications
for select to authenticated
using (
  recipient_user_id = (select auth.uid())
  and public.can_access_tenant(tenant_id)
);

drop policy if exists appointment_notifications_update_recipient
  on public.appointment_notifications;
create policy appointment_notifications_update_recipient
on public.appointment_notifications
for update to authenticated
using (
  recipient_user_id = (select auth.uid())
  and public.can_access_tenant(tenant_id)
)
with check (
  recipient_user_id = (select auth.uid())
  and public.can_access_tenant(tenant_id)
);

-- Every insertion path for appointments, including RPCs and future trusted
-- integrations, emits one notification per active membership. The function is
-- deliberately SECURITY INVOKER: it runs in the same transaction and with the
-- same privilege context as the appointment writer.
create or replace function private.create_appointment_notifications()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.appointment_notifications (
    tenant_id,
    recipient_user_id,
    appointment_id
  )
  select
    new.tenant_id,
    membership.user_id,
    new.id
  from public.tenant_memberships as membership
  where membership.tenant_id = new.tenant_id
    and membership.status = 'active'
  on conflict (recipient_user_id, appointment_id) do nothing;

  return new;
end;
$$;

revoke all on function private.create_appointment_notifications()
  from public, anon, authenticated;

drop trigger if exists trg_appointments_create_notifications
  on public.appointments;
create trigger trg_appointments_create_notifications
after insert on public.appointments
for each row
execute function private.create_appointment_notifications();

-- Realtime is opt-in per table. Keep this idempotent for environments where
-- the migration is replayed or the table was manually added previously.
do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'appointment_notifications'
  ) then
    alter publication supabase_realtime add table public.appointment_notifications;
  end if;
exception
  when duplicate_object then null;
end;
$$;
