-- Manual appointment creation with one or more saved services.
--
-- Security model:
-- - appointment service rows are readable by tenant members through RLS;
-- - browser clients cannot insert/update/delete service rows directly;
-- - the only supported browser write path is the guarded RPC below;
-- - all values that affect money, duration and snapshots are calculated server-side.

create extension if not exists btree_gist with schema extensions;

create table if not exists public.appointment_services (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  service_id bigint references public.services(id) on delete set null,
  position integer not null,
  service_name text not null,
  duration_minutes integer not null,
  unit_price numeric not null,
  created_at timestamptz not null default clock_timestamp(),
  constraint appointment_services_position_check check (position between 1 and 10),
  constraint appointment_services_duration_minutes_check check (duration_minutes > 0),
  constraint appointment_services_unit_price_check check (unit_price >= 0),
  constraint appointment_services_appointment_position_key unique (appointment_id, position)
);

comment on table public.appointment_services is
  'Snapshot dos servicos de um agendamento; valores sao calculados por create_manual_appointment.';

create index if not exists idx_appointment_services_tenant_appointment
  on public.appointment_services (tenant_id, appointment_id);

create index if not exists idx_appointment_services_service_id
  on public.appointment_services (service_id);

alter table public.appointment_services enable row level security;

revoke all on table public.appointment_services from public;
revoke all on table public.appointment_services from anon;
revoke all on table public.appointment_services from authenticated;
grant select on table public.appointment_services to authenticated;

drop policy if exists appointment_services_select_tenant on public.appointment_services;
create policy appointment_services_select_tenant
  on public.appointment_services
  for select
  to authenticated
  using ((select public.can_access_tenant(tenant_id)));

-- Read indexes for the daily Agenda and for the reservation conflict path.
create index if not exists idx_appointments_tenant_scheduled_at
  on public.appointments (tenant_id, scheduled_at desc);

create index if not exists idx_appointments_tenant_barber_scheduled_at
  on public.appointments (tenant_id, barber_id, scheduled_at);

-- Browser users retain tenant-scoped reads through the existing RLS policy, but
-- all appointment writes must use create_manual_appointment. This revocation is
-- intentionally limited to browser-facing roles: service_role and trusted
-- backend database connections remain separately privileged and must never be
-- exposed to the client.
revoke insert, update, delete on table public.appointments from public;
revoke insert, update, delete on table public.appointments from anon;
revoke insert, update, delete on table public.appointments from authenticated;
grant select on table public.appointments to authenticated;

-- Existing integration rows may omit either endpoint. When both exist they must
-- be an interval with positive duration; the manual RPC always supplies both.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.appointments'::regclass
      and conname = 'appointments_end_after_scheduled_at_check'
  ) then
    alter table public.appointments
      add constraint appointments_end_after_scheduled_at_check
      check (
        scheduled_at is null
        or end_time is null
        or end_time > scheduled_at
      ) not valid;
  end if;
end;
$$;

-- A database constraint, rather than only a pre-insert query, prevents two
-- concurrent reservations from claiming the same barber and time range.
-- Canceled/no-show appointments intentionally free the slot.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.appointments'::regclass
      and conname = 'appointments_no_active_barber_overlap'
  ) then
    alter table public.appointments
      add constraint appointments_no_active_barber_overlap
      exclude using gist (
        tenant_id with =,
        barber_id with =,
        tstzrange(scheduled_at, end_time, '[)') with &&
      )
      where (
        barber_id is not null
        and scheduled_at is not null
        and end_time is not null
        and status in ('scheduled', 'confirmed', 'pending')
      );
  end if;
end;
$$;

create or replace function public.create_manual_appointment(
  p_tenant_id text,
  p_client_id bigint,
  p_barber_id bigint,
  p_scheduled_at timestamptz,
  p_service_ids bigint[],
  p_observation text default null,
  p_status text default 'confirmed'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_client_name text;
  v_service_count integer;
  v_total_duration_minutes integer;
  v_total_price numeric;
  v_service_type text;
  v_end_time timestamptz;
  v_timezone text;
  v_observation text := nullif(pg_catalog.btrim(p_observation), '');
  v_status text := coalesce(pg_catalog.lower(pg_catalog.btrim(p_status)), '');
  v_appointment public.appointments%rowtype;
begin
  -- SECURITY DEFINER is necessary because appointment_services intentionally has
  -- no INSERT grant for authenticated browser clients. Authorization is repeated
  -- here and every lookup is scoped to the requested tenant.
  if auth.uid() is null then
    raise exception using
      errcode = '28000',
      message = 'AUTHENTICATION_REQUIRED';
  end if;

  if nullif(pg_catalog.btrim(p_tenant_id), '') is null
    or not public.can_access_tenant(p_tenant_id) then
    raise exception using
      errcode = '42501',
      message = 'TENANT_FORBIDDEN';
  end if;

  select coalesce(nullif(pg_catalog.btrim(t.timezone), ''), 'America/Sao_Paulo')
  into v_timezone
  from public.tenants as t
  where t.id = p_tenant_id;

  if v_timezone is null
    or not exists (
      select 1
      from pg_catalog.pg_timezone_names as timezone_name
      where timezone_name.name = v_timezone
    ) then
    raise exception using
      errcode = '22023',
      message = 'TENANT_TIMEZONE_INVALID';
  end if;

  if p_client_id is null or p_barber_id is null then
    raise exception using
      errcode = '22023',
      message = 'CLIENT_AND_BARBER_REQUIRED';
  end if;

  if p_scheduled_at is null or p_scheduled_at <= clock_timestamp() then
    raise exception using
      errcode = '22023',
      message = 'PAST_APPOINTMENT';
  end if;

  if v_status not in ('scheduled', 'confirmed') then
    raise exception using
      errcode = '22023',
      message = 'STATUS_INVALID';
  end if;

  if p_service_ids is null
    or cardinality(p_service_ids) not between 1 and 10 then
    raise exception using
      errcode = '22023',
      message = 'SERVICES_COUNT_INVALID';
  end if;

  if exists (
    select 1
    from unnest(p_service_ids) as requested(service_id)
    group by requested.service_id
    having count(*) > 1
  ) then
    raise exception using
      errcode = '22023',
      message = 'SERVICES_MUST_BE_DISTINCT';
  end if;

  if v_observation is not null and char_length(v_observation) > 1000 then
    raise exception using
      errcode = '22023',
      message = 'OBSERVATION_TOO_LONG';
  end if;

  select nullif(pg_catalog.btrim(c.name), '')
  into v_client_name
  from public.clients as c
  where c.id = p_client_id
    and c.tenant_id = p_tenant_id
    and c.deleted_at is null
    and coalesce(c.status, 'active') = 'active';

  if v_client_name is null then
    raise exception using
      errcode = '22023',
      message = 'CLIENT_NOT_FOUND';
  end if;

  if not exists (
    select 1
    from public.barbers as b
    where b.id = p_barber_id
      and b.tenant_id = p_tenant_id
      and coalesce(b.active, true)
      and coalesce(b.status, 'active') = 'active'
  ) then
    raise exception using
      errcode = '22023',
      message = 'BARBER_NOT_FOUND';
  end if;

  select
    count(*)::integer,
    coalesce(sum(coalesce(nullif(s.duration_minutes, 0), nullif(s.duration, 0))), 0)::integer,
    coalesce(sum(coalesce(s.price, 0)), 0),
    string_agg(s.name, ' + ' order by requested.position)
  into
    v_service_count,
    v_total_duration_minutes,
    v_total_price,
    v_service_type
  from unnest(p_service_ids) with ordinality as requested(service_id, position)
  join public.services as s
    on s.id = requested.service_id
   and s.tenant_id = p_tenant_id
   and coalesce(s.active, true)
   and coalesce(s.status, 'active') = 'active'
   and (s.barber_id is null or s.barber_id = p_barber_id)
   and coalesce(nullif(s.duration_minutes, 0), nullif(s.duration, 0)) > 0;

  if v_service_count <> cardinality(p_service_ids)
    or v_service_type is null then
    raise exception using
      errcode = '22023',
      message = 'SERVICES_INVALID';
  end if;

  if v_total_duration_minutes not between 1 and 1440
    or v_total_price < 0
    or v_total_price > 1000000 then
    raise exception using
      errcode = '22023',
      message = 'SERVICES_TOTAL_INVALID';
  end if;

  v_end_time := p_scheduled_at + make_interval(mins => v_total_duration_minutes);

  -- This lock gives a predictable domain error before the exclusion constraint
  -- and serializes competing RPC calls for the same tenant/barber. The constraint
  -- remains the authoritative protection for all writers, including legacy ones.
  perform pg_advisory_xact_lock(
    hashtextextended(p_tenant_id || ':' || p_barber_id::text, 0)
  );

  if exists (
    select 1
    from public.appointments as a
    where a.tenant_id = p_tenant_id
      and a.barber_id = p_barber_id
      and a.status in ('scheduled', 'confirmed', 'pending')
      and a.scheduled_at < v_end_time
      and a.end_time > p_scheduled_at
  ) then
    raise exception using
      errcode = '23P01',
      message = 'APPOINTMENT_CONFLICT';
  end if;

  begin
    insert into public.appointments (
      tenant_id,
      shop_id,
      user_id,
      client_id,
      barber_id,
      service_id,
      client_name,
      service_type,
      date,
      start_time,
      scheduled_at,
      end_time,
      status,
      price,
      observation
    ) values (
      p_tenant_id,
      p_tenant_id,
      p_tenant_id,
      p_client_id,
      p_barber_id,
      p_service_ids[1],
      v_client_name,
      v_service_type,
      -- The parent date is derived in the barbershop's canonical timezone,
      -- rather than the database session or browser timezone.
      (p_scheduled_at at time zone v_timezone)::date,
      p_scheduled_at,
      p_scheduled_at,
      v_end_time,
      v_status,
      v_total_price,
      v_observation
    )
    returning * into v_appointment;
  exception
    when exclusion_violation then
      raise exception using
        errcode = '23P01',
        message = 'APPOINTMENT_CONFLICT';
  end;

  insert into public.appointment_services (
    tenant_id,
    appointment_id,
    service_id,
    position,
    service_name,
    duration_minutes,
    unit_price
  )
  select
    p_tenant_id,
    v_appointment.id,
    requested.service_id,
    requested.position::integer,
    s.name,
    coalesce(nullif(s.duration_minutes, 0), nullif(s.duration, 0)),
    coalesce(s.price, 0)
  from unnest(p_service_ids) with ordinality as requested(service_id, position)
  join public.services as s
    on s.id = requested.service_id
   and s.tenant_id = p_tenant_id;

  return jsonb_build_object(
    'success', true,
    'appointment', jsonb_build_object(
      'id', v_appointment.id,
      'scheduled_at', v_appointment.scheduled_at,
      'end_time', v_appointment.end_time,
      'status', v_appointment.status,
      'price', v_appointment.price,
      'duration_minutes', v_total_duration_minutes
    ),
    'services', (
      select coalesce(
        jsonb_agg(to_jsonb(items) order by items.position),
        '[]'::jsonb
      )
      from public.appointment_services as items
      where items.appointment_id = v_appointment.id
        and items.tenant_id = p_tenant_id
    )
  );
end;
$$;

comment on function public.create_manual_appointment(text, bigint, bigint, timestamptz, bigint[], text, text) is
  'Cria um agendamento manual atomico com servicos salvos e protecao contra conflitos de horario.';

revoke all on function public.create_manual_appointment(text, bigint, bigint, timestamptz, bigint[], text, text) from public;
revoke all on function public.create_manual_appointment(text, bigint, bigint, timestamptz, bigint[], text, text) from anon;
revoke all on function public.create_manual_appointment(text, bigint, bigint, timestamptz, bigint[], text, text) from authenticated;
grant execute on function public.create_manual_appointment(text, bigint, bigint, timestamptz, bigint[], text, text) to authenticated;
